name: Purge Image

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: syossan27/purge-github-readme-image@v1.0.0
        with:
          repository: dohyeon5626/Greet
          token: ${{ secrets.GITHUB_TOKEN }}
